// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXZyR3CQd48C_MlJfe15IRcSGBJlt-w9c',
    appId: '1:1080907367525:web:2b33e75ab3c05405fe328c',
    messagingSenderId: '1080907367525',
    projectId: 'appyoyaku-83d76',
    authDomain: 'appyoyaku-83d76.firebaseapp.com',
    storageBucket: 'appyoyaku-83d76.firebasestorage.app',
    measurementId: 'G-FT1TKQGMF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMhCN4zcjNqsuGG0YCqxXtMYpbfr1tWXQ',
    appId: '1:1080907367525:android:ea82adaa4eb81b56fe328c',
    messagingSenderId: '1080907367525',
    projectId: 'appyoyaku-83d76',
    storageBucket: 'appyoyaku-83d76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSNrVk1_weA-To-aqGJ2c5VqOEDHyqlBw',
    appId: '1:1080907367525:ios:3e930a6848cefc57fe328c',
    messagingSenderId: '1080907367525',
    projectId: 'appyoyaku-83d76',
    storageBucket: 'appyoyaku-83d76.firebasestorage.app',
    iosBundleId: 'com.example.yoyaku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSNrVk1_weA-To-aqGJ2c5VqOEDHyqlBw',
    appId: '1:1080907367525:ios:3e930a6848cefc57fe328c',
    messagingSenderId: '1080907367525',
    projectId: 'appyoyaku-83d76',
    storageBucket: 'appyoyaku-83d76.firebasestorage.app',
    iosBundleId: 'com.example.yoyaku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXZyR3CQd48C_MlJfe15IRcSGBJlt-w9c',
    appId: '1:1080907367525:web:7e5d26dd07601585fe328c',
    messagingSenderId: '1080907367525',
    projectId: 'appyoyaku-83d76',
    authDomain: 'appyoyaku-83d76.firebaseapp.com',
    storageBucket: 'appyoyaku-83d76.firebasestorage.app',
    measurementId: 'G-HK1V11J9K4',
  );

}